Feature improve box queries and fix problems with rotations
konstructs/server-api pull request #14
Opened 2016-09-25 09:27 UTC by petterarvidsson

- Add box shape queries that makes it easier to ask for volumes of blocks of different shapes
- Add generic method to send events to plugins listening via universe
- Fix problems introduced code for translating rotations (figuring out which face was clicked on a rotated block)
- Add some generic helper methods and improve pretty printing

2016-09-25 09:32 UTC, petterarvidsson commented
@nsg Lots of clean-ups and new features.

2016-10-08 08:18 UTC, petterarvidsson commented
@nsg I think this stuff is ready now. Do you want to take a look at the code and more importantly the doc?

2016-10-08 11:54 UTC, nsg commented
@petterarvidsson sure! Give me a hour or so.

2016-10-08 13:03 UTC, nsg requested changes
Over all really nice, as soon we have this merged I will test it with water.

2016-10-08 13:03 UTC, nsg commented on src/main/java/konstructs/api/Box.java
> +    public Position arrayIndexAsPosition(int index) {
A public function with no docs

2016-10-08 13:03 UTC, nsg commented on src/main/java/konstructs/api/InclusiveBox.java
> + * end is inclusive and start maybe be smaller than end in all dimensions.
I understand what this sentence says, but it's a little confusing :)

2016-10-08 13:03 UTC, nsg commented on src/main/java/konstructs/api/Orientation.java
> +    public Direction translateFacePointingIn(Direction dir) {
No docs

2016-10-08 13:03 UTC, nsg commented on src/main/java/konstructs/api/Orientation.java
> +     * is rotated.
I guess these are fine, but I'm not saying that it's easy to understand. I like this "example of usage" here, maybe have more of these in hard to understand methods :)

2016-10-09 13:14 UTC, petterarvidsson commented
@nsg Pushed some documentation updates. Please have a look at them!

2016-10-09 13:17 UTC, nsg approved these changes
Looks good

2016-10-09 13:40 UTC, merged